services:
  - type: web
    name: brick-game
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_SOCKET_IO_URL
        value: https://bricks-game.onrender.com
      - key: FRONTEND_URL
        value: https://bricks-game.onrender.com
    plan: free